// Generated by https://quicktype.io

export type PokeResponse = {
	count:    number;
	next:     string;
	previous: null;
	results:  Result[];
}

export type Result = {
	name: string;
	url:  string;
}
